// Generated by CoffeeScript 1.3.1
(function() {
  var Record;

  Record = require('../Record');

  require('should');

  describe('Record', function() {
    return describe('#new', function() {
      var result;
      it('should create a new record with bound properties of the data passed in', function() {
        var data, result;
        data = {
          name: "Nick",
          age: 26
        };
        result = new Record(0, data);
        console.log(result);
        result.id.should.eql(0);
        result.name.should.eql("Nick");
        return result.age.should.eql(26);
      });
      describe('#setProperty', function() {});
      it('should set the properties of a record to match passed in data(used later for updates)', function() {
        var data;
        return data = {
          name: "Nick",
          age: 26
        };
      });
      result = new Record(0, data);
      result.setProperty(name, "Joseph");
      return result.name.should.eql("Joseph");
    });
  });

}).call(this);
